platform :ios, '11.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'MarvelComics' do
  #Network
  pod 'Alamofire', '4.6.0'
  
  #UI
  pod 'SnapKit', '4.0.0'
  pod 'NVActivityIndicatorView', '4.1.1', :inhibit_warnings => true
end